// -----------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaloriesCounter
{
    using System;

    public class FoodEntry
    {
        public double Calories { get; set; }
        public DateTime Date { get; set; }
    }
}
