//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class StyleCop : global::System.Configuration.ApplicationSettingsBase {
        
        private static StyleCop defaultInstance = ((StyleCop)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StyleCop())));
        
        public static StyleCop Default {
            get {
                return defaultInstance;
            }
        }
    }
}
